default_platform(:ios)

platform :ios do
  development_app_identifiers = ["com.twilio.LiveVideo", "com.twilio.LiveVideoUITests"]
  enterprise_app_identifiers = "com.twilio.LiveVideo"

  desc "Tests"
  lane :tests do
    run_tests
  end

  lane :ci_match_install do
    setup_circle_ci

    get_app_store_connect_api_key

    match(
      type: "development",
      app_identifier: development_app_identifiers,
      readonly: true,
      verbose: true,
      force_for_new_devices: false
    )

    match(
      type: "enterprise",
      app_identifier: enterprise_app_identifiers,
      readonly: true,
      verbose: true,
      force_for_new_devices: false
    )
  end

  desc "Install existing match certs and profiles without updating/overwriting"
  lane :match_install do
    get_app_store_connect_api_key

    match(
      type: "development",
      app_identifier: development_app_identifiers,
      readonly: true,
      verbose: true,
      force_for_new_devices: false
    )

    match(
      type: "enterprise",
      app_identifier: enterprise_app_identifiers,
      readonly: true,
      verbose: true,
      force_for_new_devices: false
    )
  end

  desc "Update and overwrite match certs and profiles if needed - destructive and may require other devs to match_install"
  lane :match_update do
    match(
      type: "development",
      app_identifier: development_app_identifiers,
      readonly: false,
      verbose: true,
      force_for_new_devices: true
    )

    match(
      type: "enterprise",
      app_identifier: enterprise_app_identifiers,
      readonly: false,
      verbose: true,
      force_for_new_devices: true
    )
  end

  private_lane :get_app_store_connect_api_key do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_B64"],
      is_key_content_base64: true,
      in_house: false
    )
  end
end
